# environment.yml
channels:
  - pytorch
  - nvidia
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pip
  - pip:
      - hydra-core
      - pyrsistent
      - omegaconf
      - e3nn
      - opt_einsum
      - opt_einsum_fx

      - -e ./env/SE3Transformer
      - -e .

      - langgraph
      - pdbfixer
      - openmm
      - biopython
      - pyyaml
